{{- if .Values.ui.ingress.enabled }}
{{- $fullName := include "continuum.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "continuum.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.ui.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ui.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.ui.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range (.paths | default (list (dict "path" "/" "pathType" "Prefix"))) }}
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: admin
          {{- end }}
    {{- end }}
{{- end }}
