// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type flowDnsPendingKey struct {
	_          structs.HostLayout
	Client     [16]uint8
	Server     [16]uint8
	ClientPort uint16
	Txid       uint16
}

type flowFlowKey struct {
	_     structs.HostLayout
	Local [16]uint8
	Peer  [16]uint8
	Port  uint16
	Role  uint8
	Pad   uint8
}

type flowFlowVal struct {
	_                 structs.HostLayout
	Connections       uint64
	BytesOut          uint64
	BytesIn           uint64
	Ifindex           int32
	Ifname            [16]int8
	Retransmits       uint32
	RtoRetransmits    uint32
	RttUs             uint32
	JitterUs          uint32
	SegsOut           uint32
	Cwnd              uint32
	_                 [4]byte
	PacingBps         uint64
	MssBytes          uint32
	RcvWnd            uint32
	SndWnd            uint32
	WmemQueued        uint32
	Sndbuf            uint32
	BufferDrops       uint32
	MeshBypassSyns    uint32
	HandshakeUs       uint32
	FailedAttempts    uint64
	FailedRefused     uint64
	FailedTimeout     uint64
	FailedReset       uint64
	FailedUnreachable uint64
}

type flowNameEvent struct {
	_     structs.HostLayout
	Saddr [16]uint8
	Daddr [16]uint8
	Sport uint16
	Dport uint16
	Kind  uint8
	Pad   [3]uint8
	Len   uint32
	Data  [1500]uint8
}

type flowSockInfo struct {
	_                  structs.HostLayout
	Key                flowFlowKey
	_                  [4]byte
	LastOut            uint64
	LastIn             uint64
	LastRetrans        uint32
	LastRtoRetransmits uint32
	LastSegsOut        uint32
	LastDrops          uint32
	SynNs              uint64
	Established        uint8
	_                  [7]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	flowMapDnsPending              = "dns_pending"
	flowMapFlows                   = "flows"
	flowMapLost                    = "lost"
	flowMapNames                   = "names"
	flowMapSnatExhaustion          = "snat_exhaustion"
	flowMapSocks                   = "socks"
	flowProgObserveEgress          = "observe_egress"
	flowProgObserveIngress         = "observe_ingress"
	flowProgOnHashConnectFexit     = "on_hash_connect_fexit"
	flowProgOnHashConnectKretprobe = "on_hash_connect_kretprobe"
	flowProgOnState                = "on_state"
	flowProgSnapshot               = "snapshot"
	flowVarUnusedNameEvent         = "unused_name_event"
)

// loadFlow returns the embedded CollectionSpec for flow.
func loadFlow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flow: %w", err)
	}

	return spec, err
}

// loadFlowObjects loads flow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowObjects
//	*flowPrograms
//	*flowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowSpecs struct {
	flowProgramSpecs
	flowMapSpecs
	flowVariableSpecs
}

// flowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowProgramSpecs struct {
	ObserveEgress          *ebpf.ProgramSpec `ebpf:"observe_egress"`
	ObserveIngress         *ebpf.ProgramSpec `ebpf:"observe_ingress"`
	OnHashConnectFexit     *ebpf.ProgramSpec `ebpf:"on_hash_connect_fexit"`
	OnHashConnectKretprobe *ebpf.ProgramSpec `ebpf:"on_hash_connect_kretprobe"`
	OnState                *ebpf.ProgramSpec `ebpf:"on_state"`
	Snapshot               *ebpf.ProgramSpec `ebpf:"snapshot"`
}

// flowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowMapSpecs struct {
	DnsPending     *ebpf.MapSpec `ebpf:"dns_pending"`
	Flows          *ebpf.MapSpec `ebpf:"flows"`
	Lost           *ebpf.MapSpec `ebpf:"lost"`
	Names          *ebpf.MapSpec `ebpf:"names"`
	SnatExhaustion *ebpf.MapSpec `ebpf:"snat_exhaustion"`
	Socks          *ebpf.MapSpec `ebpf:"socks"`
}

// flowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowVariableSpecs struct {
	UnusedNameEvent *ebpf.VariableSpec `ebpf:"unused_name_event"`
}

// flowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowObjects struct {
	flowPrograms
	flowMaps
	flowVariables
}

func (o *flowObjects) Close() error {
	return _FlowClose(
		&o.flowPrograms,
		&o.flowMaps,
	)
}

// flowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowMaps struct {
	DnsPending     *ebpf.Map `ebpf:"dns_pending"`
	Flows          *ebpf.Map `ebpf:"flows"`
	Lost           *ebpf.Map `ebpf:"lost"`
	Names          *ebpf.Map `ebpf:"names"`
	SnatExhaustion *ebpf.Map `ebpf:"snat_exhaustion"`
	Socks          *ebpf.Map `ebpf:"socks"`
}

func (m *flowMaps) Close() error {
	return _FlowClose(
		m.DnsPending,
		m.Flows,
		m.Lost,
		m.Names,
		m.SnatExhaustion,
		m.Socks,
	)
}

// flowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowVariables struct {
	UnusedNameEvent *ebpf.Variable `ebpf:"unused_name_event"`
}

// flowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowPrograms struct {
	ObserveEgress          *ebpf.Program `ebpf:"observe_egress"`
	ObserveIngress         *ebpf.Program `ebpf:"observe_ingress"`
	OnHashConnectFexit     *ebpf.Program `ebpf:"on_hash_connect_fexit"`
	OnHashConnectKretprobe *ebpf.Program `ebpf:"on_hash_connect_kretprobe"`
	OnState                *ebpf.Program `ebpf:"on_state"`
	Snapshot               *ebpf.Program `ebpf:"snapshot"`
}

func (p *flowPrograms) Close() error {
	return _FlowClose(
		p.ObserveEgress,
		p.ObserveIngress,
		p.OnHashConnectFexit,
		p.OnHashConnectKretprobe,
		p.OnState,
		p.Snapshot,
	)
}

func _FlowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flow_x86_bpfel.o
var _FlowBytes []byte
