// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type flowFlowKey struct {
	_     structs.HostLayout
	Local [16]uint8
	Peer  [16]uint8
	Port  uint16
	Role  uint8
	Pad   uint8
}

type flowFlowVal struct {
	_           structs.HostLayout
	Connections uint64
	BytesOut    uint64
	BytesIn     uint64
	Ifindex     int32
	Ifname      [16]int8
	Retransmits uint32
	RttUs       uint32
	_           [4]byte
}

type flowSockInfo struct {
	_           structs.HostLayout
	Key         flowFlowKey
	_           [4]byte
	LastOut     uint64
	LastIn      uint64
	LastRetrans uint32
	_           [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	flowMapFlows     = "flows"
	flowMapLost      = "lost"
	flowMapSocks     = "socks"
	flowProgOnState  = "on_state"
	flowProgSnapshot = "snapshot"
)

// loadFlow returns the embedded CollectionSpec for flow.
func loadFlow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flow: %w", err)
	}

	return spec, err
}

// loadFlowObjects loads flow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowObjects
//	*flowPrograms
//	*flowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowSpecs struct {
	flowProgramSpecs
	flowMapSpecs
	flowVariableSpecs
}

// flowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowProgramSpecs struct {
	OnState  *ebpf.ProgramSpec `ebpf:"on_state"`
	Snapshot *ebpf.ProgramSpec `ebpf:"snapshot"`
}

// flowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowMapSpecs struct {
	Flows *ebpf.MapSpec `ebpf:"flows"`
	Lost  *ebpf.MapSpec `ebpf:"lost"`
	Socks *ebpf.MapSpec `ebpf:"socks"`
}

// flowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowVariableSpecs struct {
}

// flowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowObjects struct {
	flowPrograms
	flowMaps
	flowVariables
}

func (o *flowObjects) Close() error {
	return _FlowClose(
		&o.flowPrograms,
		&o.flowMaps,
	)
}

// flowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowMaps struct {
	Flows *ebpf.Map `ebpf:"flows"`
	Lost  *ebpf.Map `ebpf:"lost"`
	Socks *ebpf.Map `ebpf:"socks"`
}

func (m *flowMaps) Close() error {
	return _FlowClose(
		m.Flows,
		m.Lost,
		m.Socks,
	)
}

// flowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowVariables struct {
}

// flowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowPrograms struct {
	OnState  *ebpf.Program `ebpf:"on_state"`
	Snapshot *ebpf.Program `ebpf:"snapshot"`
}

func (p *flowPrograms) Close() error {
	return _FlowClose(
		p.OnState,
		p.Snapshot,
	)
}

func _FlowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flow_arm64_bpfel.o
var _FlowBytes []byte
